In [39]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split, cross_val_score;


In [13]:
path_to_train = 'Train.txt'
path_to_CV = 'Cross_Validation.txt'
path_to_test = 'Test.txt'

train_data = pd.read_csv(path_to_train, header = None, sep = '#|;', engine = 'python')
CV_data = pd.read_csv(path_to_CV, header = None, sep = '#|;', engine = 'python')
test_data = pd.read_csv(path_to_test, header = None, sep = '#|;', engine = 'python')

In [14]:
y_train = np.array(train_data.iloc[:, 0])
x_train = np.array(train_data.iloc[:, 1:])

y_CV = np.array(CV_data.iloc[:, 0])
x_CV = np.array(CV_data.iloc[:, 1:])

y_test = np.array(test_data.iloc[:, 0])
x_test = np.array(test_data.iloc[:, 1:])


In [15]:
scaler = StandardScaler()
scaler.fit(x_train)

x_train = scaler.transform(x_train)

x_CV = scaler.transform(x_CV)

x_test = scaler.transform(x_test)

In [99]:
clf = MLPClassifier(hidden_layer_sizes=(150,150,150), max_iter=200, alpha=0.0001,
                     solver='adam', verbose=True,  random_state=22,tol=0.000000001)

In [100]:
clf.fit(x_train, y_train)

Iteration 1, loss = 0.84976923
Iteration 2, loss = 0.13881454
Iteration 3, loss = 0.06484710
Iteration 4, loss = 0.03348883
Iteration 5, loss = 0.01635386
Iteration 6, loss = 0.00857231
Iteration 7, loss = 0.00379405
Iteration 8, loss = 0.00213314
Iteration 9, loss = 0.00155387
Iteration 10, loss = 0.00124641
Iteration 11, loss = 0.00104129
Iteration 12, loss = 0.00089430
Iteration 13, loss = 0.00078169
Iteration 14, loss = 0.00069139
Iteration 15, loss = 0.00062254
Iteration 16, loss = 0.00056747
Iteration 17, loss = 0.00052387
Iteration 18, loss = 0.00048018
Iteration 19, loss = 0.00044784
Iteration 20, loss = 0.00041991
Iteration 21, loss = 0.00039530
Iteration 22, loss = 0.00037536
Iteration 23, loss = 0.00035696
Iteration 24, loss = 0.00034120
Iteration 25, loss = 0.00032740
Iteration 26, loss = 0.00031556
Iteration 27, loss = 0.00030485
Iteration 28, loss = 0.00029487
Iteration 29, loss = 0.00028617
Iteration 30, loss = 0.00027826
Iteration 31, loss = 0.00027144
Iteration 32, los

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(150, 150, 150), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=200,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=22, shuffle=True, solver='adam',
              tol=1e-09, validation_fraction=0.1, verbose=True,
              warm_start=False)

In [91]:
scores = -1 * cross_val_score(clf, x_CV, y_CV, cv=5, scoring='neg_mean_absolute_error');
print("Cross-Validation score: ", scores.mean())

Iteration 1, loss = 3.14344957
Iteration 2, loss = 2.49779927
Iteration 3, loss = 2.04118346
Iteration 4, loss = 1.64041217
Iteration 5, loss = 1.25372524
Iteration 6, loss = 0.94126640
Iteration 7, loss = 0.72417715
Iteration 8, loss = 0.54106577
Iteration 9, loss = 0.41591324
Iteration 10, loss = 0.34347897
Iteration 11, loss = 0.26178882
Iteration 12, loss = 0.22433117
Iteration 13, loss = 0.18756613
Iteration 14, loss = 0.14355950
Iteration 15, loss = 0.11063382
Iteration 16, loss = 0.08474401
Iteration 17, loss = 0.06776675
Iteration 18, loss = 0.05111701
Iteration 19, loss = 0.04512973
Iteration 20, loss = 0.04428725
Iteration 21, loss = 0.03395877
Iteration 22, loss = 0.02704634
Iteration 23, loss = 0.02351722
Iteration 24, loss = 0.02025200
Iteration 25, loss = 0.01864246
Iteration 26, loss = 0.01615368
Iteration 27, loss = 0.01477279
Iteration 28, loss = 0.01322771
Iteration 29, loss = 0.01218614
Iteration 30, loss = 0.01152515
Iteration 31, loss = 0.01078980
Iteration 32, los

C:\Users\User\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)



Iteration 7, loss = 0.65803362
Iteration 8, loss = 0.48814498
Iteration 9, loss = 0.36494213
Iteration 10, loss = 0.28412684
Iteration 11, loss = 0.21133940
Iteration 12, loss = 0.17268480
Iteration 13, loss = 0.12994280
Iteration 14, loss = 0.09950701
Iteration 15, loss = 0.08704191
Iteration 16, loss = 0.07345828
Iteration 17, loss = 0.05389249
Iteration 18, loss = 0.04162482
Iteration 19, loss = 0.03858278
Iteration 20, loss = 0.03574212
Iteration 21, loss = 0.02591015
Iteration 22, loss = 0.02154699
Iteration 23, loss = 0.01867802
Iteration 24, loss = 0.01583238
Iteration 25, loss = 0.01400569
Iteration 26, loss = 0.01237323
Iteration 27, loss = 0.01130213
Iteration 28, loss = 0.01047639
Iteration 29, loss = 0.00960921
Iteration 30, loss = 0.00871164
Iteration 31, loss = 0.00797931
Iteration 32, loss = 0.00728747
Iteration 33, loss = 0.00670061
Iteration 34, loss = 0.00640892
Iteration 35, loss = 0.00623187
Iteration 36, loss = 0.00576222
Iteration 37, loss = 0.00542005
Iteration 

C:\Users\User\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


Iteration 3, loss = 1.99420916
Iteration 4, loss = 1.56996711
Iteration 5, loss = 1.19113454
Iteration 6, loss = 0.86678846
Iteration 7, loss = 0.64203600
Iteration 8, loss = 0.46685513
Iteration 9, loss = 0.35138976
Iteration 10, loss = 0.26598059
Iteration 11, loss = 0.19882744
Iteration 12, loss = 0.15837609
Iteration 13, loss = 0.13080034
Iteration 14, loss = 0.09833284
Iteration 15, loss = 0.08052229
Iteration 16, loss = 0.06496774
Iteration 17, loss = 0.04838812
Iteration 18, loss = 0.03952306
Iteration 19, loss = 0.03259305
Iteration 20, loss = 0.02617325
Iteration 21, loss = 0.02167020
Iteration 22, loss = 0.01974457
Iteration 23, loss = 0.01710699
Iteration 24, loss = 0.01468240
Iteration 25, loss = 0.01329068
Iteration 26, loss = 0.01172301
Iteration 27, loss = 0.01053365
Iteration 28, loss = 0.01005779
Iteration 29, loss = 0.00920918
Iteration 30, loss = 0.00827664
Iteration 31, loss = 0.00795619
Iteration 32, loss = 0.00785852
Iteration 33, loss = 0.00708500
Iteration 34, l

C:\Users\User\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)



Iteration 3, loss = 1.99904999
Iteration 4, loss = 1.57285338
Iteration 5, loss = 1.18336032
Iteration 6, loss = 0.86254125
Iteration 7, loss = 0.64258266
Iteration 8, loss = 0.47302406
Iteration 9, loss = 0.35819892
Iteration 10, loss = 0.27760233
Iteration 11, loss = 0.21390045
Iteration 12, loss = 0.16325540
Iteration 13, loss = 0.12604739
Iteration 14, loss = 0.10153205
Iteration 15, loss = 0.07909735
Iteration 16, loss = 0.06386763
Iteration 17, loss = 0.05174308
Iteration 18, loss = 0.04344664
Iteration 19, loss = 0.03442412
Iteration 20, loss = 0.03138279
Iteration 21, loss = 0.02342817
Iteration 22, loss = 0.02085633
Iteration 23, loss = 0.01722819
Iteration 24, loss = 0.01470801
Iteration 25, loss = 0.01345226
Iteration 26, loss = 0.01240086
Iteration 27, loss = 0.01104990
Iteration 28, loss = 0.00994078
Iteration 29, loss = 0.00904424
Iteration 30, loss = 0.00833445
Iteration 31, loss = 0.00773496
Iteration 32, loss = 0.00724282
Iteration 33, loss = 0.00675852
Iteration 34, 

C:\Users\User\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


Iteration 5, loss = 1.16367555
Iteration 6, loss = 0.84113570
Iteration 7, loss = 0.63515440
Iteration 8, loss = 0.45908230
Iteration 9, loss = 0.34087722
Iteration 10, loss = 0.27287889
Iteration 11, loss = 0.20390922
Iteration 12, loss = 0.16466906
Iteration 13, loss = 0.12970738
Iteration 14, loss = 0.09757304
Iteration 15, loss = 0.07946281
Iteration 16, loss = 0.06678591
Iteration 17, loss = 0.05307080
Iteration 18, loss = 0.04051491
Iteration 19, loss = 0.03670170
Iteration 20, loss = 0.03368638
Iteration 21, loss = 0.02185983
Iteration 22, loss = 0.02144309
Iteration 23, loss = 0.01752925
Iteration 24, loss = 0.01453787
Iteration 25, loss = 0.01424422
Iteration 26, loss = 0.01449477
Iteration 27, loss = 0.01248529
Iteration 28, loss = 0.01600768
Iteration 29, loss = 0.01228425
Iteration 30, loss = 0.00981823
Iteration 31, loss = 0.00862428
Iteration 32, loss = 0.00761899
Iteration 33, loss = 0.00677204
Iteration 34, loss = 0.00614934
Iteration 35, loss = 0.00594394
Iteration 36,

C:\Users\User\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [97]:
clf_train_predict = clf.predict(x_train)
print("For train data accuracy: ", accuracy_score(y_train, clf_train_predict)) 

clf_CV_predict = clf.predict(x_CV)
print("For Cross-validation:", accuracy_score(y_CV, clf_CV_predict))

clf_test_predict = clf.predict(x_test)
print("For test data:", accuracy_score(y_test, clf_test_predict)) #very good i think :)
print(confusion_matrix(y_test, clf_test_predict))
print(classification_report(y_test, clf_test_predict))

For train data accuracy:  1.0
For Cross-validation: 0.9871287128712871
For test data: 0.981169474727453
[[34  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 50  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0]
 [ 0  0 47  0  0  0  0  0  0  0  0  0  2  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 38  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 33  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1]
 [ 0  0  0  0  0 52  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 48  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 50  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 40  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 31  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 44  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 37  0  0  0  0  0  0  0  0  0  0  0 

In [104]:
dec_clf = DecisionTreeClassifier(criterion='entropy', random_state=22, max_depth = 100, min_samples_leaf = 2)


In [105]:
dec_clf.fit(x_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=100, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=2, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=22, splitter='best')

In [106]:
dec_train_predict = dec_clf.predict(x_train)
print("For train data accuracy: ", accuracy_score(y_train, dec_train_predict)) 

dec_CV_predict = dec_clf.predict(x_CV)
print("For Cross-validation:", accuracy_score(y_CV, dec_CV_predict))

dec_test_predict = dec_clf.predict(x_test)
print("For test data:", accuracy_score(y_test, dec_test_predict)) #pretty good i think :)
print(confusion_matrix(y_test, dec_test_predict))
print(classification_report(y_test, dec_test_predict))

For train data accuracy:  0.972041827187672
For Cross-validation: 0.7712871287128713
For test data: 0.7869177403369673
[[30  2  1  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  1  0  0]
 [ 0 40  0  1  2  1  0  0  0  4  0  0  0  0  1  0  0  0  1  0  1  0  0  0]
 [ 0  1 33  3  0  0  0  1  1  1  0  4  0  0  1  0  1  1  0  2  0  0  0  0]
 [ 2  1  1 31  0  0  0  0  1  0  0  1  0  1  0  0  0  0  0  0  0  0  0  0]
 [ 1  0  0  0 25  3  0  2  0  0  0  0  0  1  0  0  0  0  0  1  1  1  0  0]
 [ 0  1  0  0  2 42  0  2  0  3  0  2  0  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1 45  0  0  0  0  1  1  0  0  0  0  0  0  0  0  1  0  0]
 [ 0  0  0  0  0  2  0 48  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  0  0  0  0 38  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  1  0  1  0  0  0  0 23  0  0  0  0  0  2  0  1  1  1  0  0  0  0]
 [ 0  2  0  0  0  0  0  0  0  3 34  0  0  0  1  0  0  2  0  0  0  0  0  2]
 [ 0  0  1  0  1  0  1  0  2  0  0 30  0  0  0  0  0  0 